### ISSUE TITLE
Repository over LFS data quota error.

### ISSUE THREAD

**Issue by guichristmann** [mediakind-video/effortless-performance-improvements-cpp#1]
Hi, thank you for the blog posts and repo. I want to follow along and learn more about C++ performance.

Cloning the repo gave me this error:
```
Error downloading object: reference/sample-10.txt.gz (ec2ce70): Smudge error: Error downloading reference/sample-10.txt.gz (ec2ce70be94555d0ff707a5a8d75a2e2785942437cff5cfc9abe6420e7aa2f21): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

**Comment by j-jorge** [comment]
Hello,
The quotas should be reset in a few days, allowing for cloning again. Until then I would suggest to download the zip from master via GitHub's UI. It would not contain the sample inputs (the .gz files) but you can generate new ones with the included `generator` application.

**Comment by guichristmann** [comment]
Got it. Thanks for the clarification :+1:
